# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasupplier',
            name='suppliercode',
            field=models.CharField(db_column='SupplierCode', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
