# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-24 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naaccfa',
            name='is_parent',
            field=models.PositiveSmallIntegerField(db_column='IsParent', default=0),
        ),
    ]
