# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napriviledge',
            name='last_form',
            field=models.CharField(db_column='Last_form', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='napriviledge',
            name='last_login',
            field=models.DateTimeField(db_column='Last_login', null=True),
        ),
        migrations.AlterField(
            model_name='napriviledge',
            name='role',
            field=models.IntegerField(choices=[(3, 'Guest'), (2, 'User'), (1, 'Super User')], db_column='Role', default=3, null=True),
        ),
    ]
