# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAGaReceive',
            fields=[
                ('idapp', models.AutoField(db_column='IDApp', primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField(db_column='CreatedDate', default=django.utils.timezone.now)),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=100)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('brand', models.CharField(db_column='Brand', max_length=100)),
                ('invoce_no', models.CharField(blank=True, db_column='Invoce_No', max_length=100, null=True)),
                ('fk_app', models.IntegerField(db_column='FK_App')),
                ('typeapp', models.CharField(blank=True, db_column='TypeApp', max_length=64, null=True)),
                ('machine_no', models.CharField(db_column='Machine_No', max_length=50, unique=True)),
                ('chasis_no', models.CharField(db_column='Chasis_No', max_length=50)),
                ('year_made', models.DateField(db_column='Year_Made')),
                ('colour', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=100, null=True)),
                ('kind', models.CharField(blank=True, db_column='Kind', max_length=30, null=True)),
                ('cylinder', models.CharField(blank=True, db_column='Cylinder', max_length=20, null=True)),
                ('fuel', models.CharField(blank=True, db_column='Fuel', max_length=20, null=True)),
                ('descriptions', models.CharField(blank=True, db_column='Descriptions', max_length=200, null=True)),
            ],
            options={
                'db_table': 'na_ga_receive',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='NaGaDetail',
        ),
    ]
