# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nagareceive',
            table='n_a_ga_receive',
        ),
    ]
