# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0002_auto_20180710_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAGaOutwards',
            fields=[
                ('idapp', models.AutoField(db_column='IDApp', primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField(db_column='CreatedDate', default=django.utils.timezone.now)),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=100)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('typeapp', models.CharField(db_column='TypeApp', max_length=32)),
                ('serialnumber', models.CharField(db_column='SerialNumber', default='N/A', max_length=100)),
                ('isnew', models.BooleanField(db_column='IsNew')),
                ('daterequest', models.DateTimeField(db_column='DateRequest')),
                ('datereleased', models.DateTimeField(db_column='DateReleased')),
                ('lastinfo', models.CharField(blank=True, db_column='lastinfo', max_length=150, null=True)),
                ('descriptions', models.CharField(blank=True, db_column='Descriptions', max_length=250, null=True)),
                ('equipment', models.CharField(blank=True, db_column='Equipment', max_length=200, null=True)),
                ('add_equipment', models.CharField(blank=True, db_column='Add_Equipment', max_length=200, null=True)),
            ],
            options={
                'db_table': 'n_a_ga_outwards',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_frommaintenance',
            field=models.ForeignKey(blank=True, db_column='FK_FromMaintenance', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_maintenance_nagoodsoutwards', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_lending',
            field=models.ForeignKey(blank=True, db_column='FK_Lending', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_lending_nagoodsoutwards', to='NA_Models.NAGoodsLending'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_receive',
            field=models.ForeignKey(db_column='FK_Receive', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_receive_nagoodsoutwards', to='NA_Models.NAGoodsReceive'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_responsibleperson',
            field=models.ForeignKey(blank=True, db_column='FK_ResponsiblePerson', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_resp_person_nagoodsoutwards', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_return',
            field=models.ForeignKey(db_column='FK_Return', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_return_nagoodsoutwards', to='NA_Models.NAGoodsReturn'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_sender',
            field=models.ForeignKey(blank=True, db_column='FK_Sender', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_sender_nagoodsoutwards', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_stock',
            field=models.ForeignKey(blank=True, db_column='FK_Stock', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_stock_nagoodsoutwards', to='NA_Models.NAStock'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_usedemployee',
            field=models.ForeignKey(db_column='FK_UsedEmployee', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_used_employee_nagoodsoutwards', to='NA_Models.Employee'),
        ),
        migrations.AlterModelTable(
            name='nagavnhistory',
            table='n_a_ga_vn_history',
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_app',
            field=models.ForeignKey(db_column='fk_app', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGaVnHistory'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_employee',
            field=models.ForeignKey(db_column='FK_Employee', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.Employee'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_frommaintenance',
            field=models.ForeignKey(blank=True, db_column='FK_FromMaintenance', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_maintenance_nagaoutwards', to='NA_Models.Employee'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_lending',
            field=models.ForeignKey(blank=True, db_column='FK_Lending', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_lending_nagaoutwards', to='NA_Models.NAGoodsLending'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_receive',
            field=models.ForeignKey(db_column='FK_Receive', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_receive_nagaoutwards', to='NA_Models.NAGoodsReceive'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_responsibleperson',
            field=models.ForeignKey(blank=True, db_column='FK_ResponsiblePerson', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_resp_person_nagaoutwards', to='NA_Models.Employee'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_return',
            field=models.ForeignKey(db_column='FK_Return', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_return_nagaoutwards', to='NA_Models.NAGoodsReturn'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_sender',
            field=models.ForeignKey(blank=True, db_column='FK_Sender', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_sender_nagaoutwards', to='NA_Models.Employee'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_stock',
            field=models.ForeignKey(blank=True, db_column='FK_Stock', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_stock_nagaoutwards', to='NA_Models.NAStock'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='fk_usedemployee',
            field=models.ForeignKey(db_column='FK_UsedEmployee', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_used_employee_nagaoutwards', to='NA_Models.Employee'),
        ),
    ]
