# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-19 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0002_auto_20180815_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='nadisposal',
            name='fk_lost',
            field=models.ForeignKey(blank=True, db_column='FK_Lost', null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsLost'),
        ),
        migrations.AlterField(
            model_name='nadisposal',
            name='fk_sold_to_employee',
            field=models.ForeignKey(blank=True, db_column='FK_Sold_To_Employee', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_disposal_emp_Sold', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagamaintenance',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
    ]
