# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0002_auto_20180611_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nasyspriviledge',
            unique_together=set([('fk_p_form', 'permission', 'user_id')]),
        ),
    ]
