# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0002_naaccfa_is_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAGoodsEquipment',
            fields=[
                ('idapp', models.AutoField(db_column='IDApp', primary_key=True, serialize=False)),
                ('name_app', models.CharField(db_column='NameApp', max_length=50)),
                ('type_app', models.IntegerField(choices=[(1, 'GA'), (0, 'IT')], db_column='TypeApp')),
            ],
            options={
                'db_table': 'n_a_equipment',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='typeapp',
            field=models.CharField(choices=[('IT', 'IT'), ('GA', 'GA'), ('IT Accessories', 'IT Accessories'), ('GA Accesories', 'GA Accesories'), ('Others', 'Others')], db_column='typeapp', max_length=32, null=True),
        ),
        migrations.RemoveField(
            model_name='nagaoutwards',
            name='add_equipment',
        ),
        migrations.RemoveField(
            model_name='nagaoutwards',
            name='equipment',
        ),
        migrations.AlterField(
            model_name='napriviledge_form',
            name='form_name_ori',
            field=models.CharField(choices=[('employee', 'employee'), ('n_a_suplier', 'n_a_suplier'), ('goods', 'goods'), ('n_a_goods_receive', 'n_a_goods_receive'), ('n_a_priviledge', 'n_a_priviledge'), ('n_a_acc_fa', 'n_a_acc_fa')], db_column='Form_name_ori', max_length=50),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='add_equipment',
            field=models.ManyToManyField(db_column='AddEquipment', db_constraint=False, related_name='ga_add_equipment', to='NA_Models.NAGoodsEquipment'),
        ),
        migrations.AddField(
            model_name='nagaoutwards',
            name='equipment',
            field=models.ManyToManyField(db_column='Equipment', db_constraint=False, related_name='ga_equipment', to='NA_Models.NAGoodsEquipment'),
        ),
    ]
