# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0003_auto_20180714_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagareceive',
            name='price',
            field=models.DecimalField(db_column='Price', decimal_places=4, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nadisposal',
            name='fk_acc_fa',
            field=models.ForeignKey(blank=True, db_column='FK_Acc_FA', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_disposal_accfa', to='NA_Models.NAAccFa'),
        ),
        migrations.AlterField(
            model_name='nadisposal',
            name='fk_maintenance',
            field=models.ForeignKey(blank=True, db_column='FK_Maintenance', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_disposal_maintenance', to='NA_Models.NAMaintenance'),
        ),
        migrations.AlterField(
            model_name='nadisposal',
            name='fk_stock',
            field=models.ForeignKey(blank=True, db_column='FK_Stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_disposal_stock', to='NA_Models.NAStock'),
        ),
        migrations.AlterField(
            model_name='nadisposal',
            name='issold',
            field=models.PositiveSmallIntegerField(blank=True, db_column='IsSold', null=True),
        ),
    ]
