# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 22:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0003_auto_20180612_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logevent',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='nagoodsreturn',
            name='fk_employee',
        ),
        migrations.AddField(
            model_name='nagoodslending',
            name='datereturn',
            field=models.DateTimeField(db_column='DateReturn', null=True),
        ),
        migrations.AddField(
            model_name='nagoodslost',
            name='datelost',
            field=models.DateTimeField(db_column='DateLost', default=datetime.datetime(2018, 6, 20, 22, 28, 34, 974230)),
        ),
        migrations.AddField(
            model_name='nagoodsoutwards',
            name='descriptions',
            field=models.CharField(blank=True, db_column='Descriptions', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nagoodsoutwards',
            name='lastinfo',
            field=models.CharField(blank=True, db_column='lastinfo', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='logevent',
            name='createdby',
            field=models.CharField(db_column='CreatedBy', max_length=100),
        ),
        migrations.AlterField(
            model_name='na_goodsreceive_detail',
            name='fk_app',
            field=models.ForeignKey(db_column='FK_App', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsReceive'),
        ),
        migrations.AlterField(
            model_name='naaccfa',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='AccFA_goods', to='NA_Models.goods'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_currentapp',
            field=models.ForeignKey(blank=True, db_column='FK_CurrentApp', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_gl_parent', to='NA_Models.NAGoodsLending'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_employee',
            field=models.ForeignKey(db_column='FK_Employee', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_maintenance',
            field=models.ForeignKey(blank=True, db_column='FK_Maintenance', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_gl_maintenance', to='NA_Models.NAMaintenance'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_receive',
            field=models.ForeignKey(blank=True, db_column='FK_Receive', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_gl_goods_receive', to='NA_Models.NAGoodsReceive'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_responsibleperson',
            field=models.ForeignKey(blank=True, db_column='FK_ResponsiblePerson', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_gl_employee_resp_person', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_return',
            field=models.ForeignKey(blank=True, db_column='FK_RETURN', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_gl_goods_return', to='NA_Models.NAGoodsReturn'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_sender',
            field=models.ForeignKey(blank=True, db_column='FK_Sender', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_gl_employee_sender', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='fk_stock',
            field=models.ForeignKey(db_column='FK_Stock', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='fk_gl_stock', to='NA_Models.NAStock'),
        ),
        migrations.AlterField(
            model_name='nagoodslending',
            name='lastinfo',
            field=models.CharField(blank=True, db_column='lastinfo', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nagoodslost',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AlterField(
            model_name='nagoodslost',
            name='fk_goods_lending',
            field=models.ForeignKey(blank=True, db_column='FK_Goods_Lending', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsLending'),
        ),
        migrations.AlterField(
            model_name='nagoodslost',
            name='fk_goods_outwards',
            field=models.ForeignKey(blank=True, db_column='FK_Goods_Outwards', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsOutwards'),
        ),
        migrations.AlterField(
            model_name='nagoodslost',
            name='fk_lostby',
            field=models.ForeignKey(blank=True, db_column='FK_LostBy', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_by', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodslost',
            name='fk_maintenance',
            field=models.ForeignKey(blank=True, db_column='FK_Maintenance', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAMaintenance'),
        ),
        migrations.AlterField(
            model_name='nagoodslost',
            name='fk_responsibleperson',
            field=models.ForeignKey(blank=True, db_column='FK_ResponsiblePerson', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resp_person_goods_lost', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodslost',
            name='fk_usedby',
            field=models.ForeignKey(blank=True, db_column='FK_UsedBy', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_employee',
            field=models.ForeignKey(db_column='FK_Employee', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_frommaintenance',
            field=models.ForeignKey(blank=True, db_column='FK_FromMaintenance', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_maintenance_outwards', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_lending',
            field=models.ForeignKey(blank=True, db_column='FK_Lending', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_lending_outwards', to='NA_Models.NAGoodsLending'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_receive',
            field=models.ForeignKey(db_column='FK_Receive', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_receive_outward', to='NA_Models.NAGoodsReceive'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_responsibleperson',
            field=models.ForeignKey(blank=True, db_column='FK_ResponsiblePerson', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_resp_person_outwards', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_return',
            field=models.ForeignKey(db_column='FK_Return', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_return_outwards', to='NA_Models.NAGoodsLending'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_sender',
            field=models.ForeignKey(blank=True, db_column='FK_Sender', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_sender_outwards', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_stock',
            field=models.ForeignKey(blank=True, db_column='FK_Stock', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_stock_outwards', to='NA_Models.NAStock'),
        ),
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_usedemployee',
            field=models.ForeignKey(db_column='FK_UsedEmployee', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_used_employee_outwards', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive',
            name='fk_suplier',
            field=models.ForeignKey(db_column='FK_Suplier', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NASuplier'),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive',
            name='idapp_fk_goods',
            field=models.ForeignKey(db_column='fk_goods', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive',
            name='idapp_fk_p_r_by',
            field=models.ForeignKey(blank=True, db_column='FK_P_R_By', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_p_r_by', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive',
            name='idapp_fk_receivedby',
            field=models.ForeignKey(db_column='FK_ReceivedBy', db_constraint=False, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='fk_receivedBy', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive_other',
            name='fk_goods',
            field=models.ForeignKey(db_column='fk_goods', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive_other',
            name='fk_p_r_by',
            field=models.ForeignKey(blank=True, db_column='FK_P_R_By', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_p_r_by_other', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive_other',
            name='fk_receivedby',
            field=models.ForeignKey(db_column='FK_ReceivedBy', db_constraint=False, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='fk_receivedBy_other', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive_other',
            name='fk_suplier',
            field=models.ForeignKey(db_column='FK_Suplier', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NASuplier'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='descriptions',
            field=models.CharField(blank=True, db_column='Descriptions', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_fromemployee',
            field=models.ForeignKey(blank=True, db_column='FK_FromEmployee', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ngr_fromemployee', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_goods_lend',
            field=models.ForeignKey(blank=True, db_column='FK_Goods_Lend', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsLending'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_goods_outwards',
            field=models.ForeignKey(blank=True, db_column='FK_Goods_Outwards', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsOutwards'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_usedemployee',
            field=models.ForeignKey(blank=True, db_column='FK_UsedEmployee', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ngr_usedemployee', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='namaintenance',
            name='descriptions',
            field=models.CharField(blank=True, db_column='Descriptions', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='namaintenance',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AlterField(
            model_name='nasyspriviledge',
            name='fk_p_form',
            field=models.ForeignKey(db_column='FK_PForm', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAPriviledge_form'),
        ),
        migrations.AlterField(
            model_name='nasyspriviledge',
            name='user_id',
            field=models.ForeignKey(db_column='User_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
