# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-27 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0003_auto_20180911_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='na_goodsreceive_detail',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='nagoodsreceive',
            name='descbysystem',
            field=models.CharField(blank=True, db_column='DescBySystem', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive',
            name='refno',
            field=models.CharField(db_column='REFNO', max_length=100),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive_other',
            name='descbysystem',
            field=models.CharField(blank=True, db_column='DescBySystem', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nagoodsreceive_other',
            name='refno',
            field=models.CharField(db_column='REFNO', max_length=100),
        ),
    ]
