# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0004_auto_20180620_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='nastock',
            name='t_goods_spare',
            field=models.PositiveSmallIntegerField(db_column='T_Goods_Spare', null=True),
        ),
        migrations.AlterField(
            model_name='nagoodslost',
            name='datelost',
            field=models.DateTimeField(db_column='DateLost', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nastock',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
    ]
