# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0004_auto_20180927_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagoodsoutwards',
            name='equipment_desc',
            field=models.CharField(blank=True, db_column='Equipment_Desc', max_length=400, null=True),
        ),
    ]
