# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-21 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0004_auto_20180718_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAGAReturn',
            fields=[
                ('idapp', models.AutoField(db_column='IDApp', primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField(db_column='CreatedDate', default=django.utils.timezone.now)),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=100)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('typeapp', models.CharField(db_column='TypeApp', max_length=32)),
                ('serialnumber', models.CharField(db_column='SerialNumber', default='N/A', max_length=100)),
                ('datereturn', models.DateTimeField(db_column='DateReturn')),
                ('conditions', models.CharField(db_column='Conditions', max_length=1)),
                ('iscompleted', models.PositiveSmallIntegerField(db_column='IsCompleted')),
                ('minusDesc', models.CharField(blank=True, db_column='MinusDesc', max_length=100, null=True)),
                ('descriptions', models.CharField(blank=True, db_column='Descriptions', max_length=250, null=True)),
                ('fk_fromemployee', models.ForeignKey(blank=True, db_column='FK_FromEmployee', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ngr_fromemployee_nagareturn', to='NA_Models.Employee')),
            ],
            options={
                'db_table': 'n_a_ga_return',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='nadisposal',
            name='FK_ResponsiblePerson',
        ),
        migrations.RemoveField(
            model_name='nadisposal',
            name='ishasvalue',
        ),
        migrations.RemoveField(
            model_name='nagaoutwards',
            name='fk_lending',
        ),
        migrations.RemoveField(
            model_name='nagaoutwards',
            name='serialnumber',
        ),
        migrations.AddField(
            model_name='naaccfa',
            name='date_depreciation',
            field=models.DateField(db_column='DateDepreciation', null=True),
        ),
        migrations.AddField(
            model_name='nadisposal',
            name='fk_lending',
            field=models.ForeignKey(blank=True, db_column='FK_Lending', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_disposal_lending', to='NA_Models.NAGoodsLending'),
        ),
        migrations.AddField(
            model_name='nadisposal',
            name='fk_proposedby',
            field=models.ForeignKey(blank=True, db_column='FK_ProposedBy', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_disposal_emp_proposed', to='NA_Models.Employee'),
        ),
        migrations.AddField(
            model_name='nadisposal',
            name='fk_return',
            field=models.ForeignKey(blank=True, db_column='FK_Return', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_disposal_return', to='NA_Models.NAGoodsReturn'),
        ),
        migrations.AddField(
            model_name='nadisposal',
            name='fk_usedemployee',
            field=models.ForeignKey(blank=True, db_column='FK_UsedEmployee', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_disposal_emp_used', to='NA_Models.Employee'),
        ),
        migrations.AddField(
            model_name='nadisposal',
            name='islost',
            field=models.PositiveSmallIntegerField(db_column='IsLost', default=0),
        ),
        migrations.AddField(
            model_name='nadisposal',
            name='modifiedby',
            field=models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nadisposal',
            name='modifieddate',
            field=models.DateTimeField(blank=True, db_column='ModifiedDate', null=True),
        ),
        migrations.AddField(
            model_name='nagavnhistory',
            name='fk_parent',
            field=models.ForeignKey(blank=True, db_column='FK_Parent', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGaVnHistory'),
        ),
        migrations.AddField(
            model_name='nagavnhistory',
            name='purpose',
            field=models.CharField(blank=True, choices=[('extends', 'extends'), ('lost', 'lost'), ('other', 'other')], db_column='Purpose', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nagavnhistory',
            name='fk_app',
            field=models.ForeignKey(db_column='FK_App', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGaReceive'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_fromemployee',
            field=models.ForeignKey(blank=True, db_column='FK_FromEmployee', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ngr_fromemployee_nagoodsreturn', to='NA_Models.Employee'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_goods_lend',
            field=models.ForeignKey(blank=True, db_column='FK_Goods_Lend', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_lend_nagoodsreturn', to='NA_Models.NAGoodsLending'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_goods_outwards',
            field=models.ForeignKey(blank=True, db_column='FK_Goods_Outwards', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_outwards_nagoodsreturn', to='NA_Models.NAGoodsOutwards'),
        ),
        migrations.AlterField(
            model_name='nagoodsreturn',
            name='fk_usedemployee',
            field=models.ForeignKey(blank=True, db_column='FK_UsedEmployee', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ngr_usedemployee_nagoodsreturn', to='NA_Models.Employee'),
        ),
        migrations.AddField(
            model_name='nagareturn',
            name='fk_ga_outwards',
            field=models.ForeignKey(blank=True, db_column='fk_ga_outwards', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGaOutwards'),
        ),
        migrations.AddField(
            model_name='nagareturn',
            name='fk_goods',
            field=models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods'),
        ),
        migrations.AddField(
            model_name='nagareturn',
            name='fk_usedemployee',
            field=models.ForeignKey(blank=True, db_column='FK_UsedEmployee', db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ngr_usedemployee_nagareturn', to='NA_Models.Employee'),
        ),
    ]
