# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-22 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0005_auto_20180721_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nagavnhistory',
            name='bpkp_expired',
        ),
        migrations.AddField(
            model_name='nagavnhistory',
            name='bpkb_expired',
            field=models.DateField(blank=True, db_column='BPKB_Expired', null=True),
        ),
    ]
