# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0005_auto_20180620_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nastock',
            name='tgoods_recieved',
        ),
        migrations.AddField(
            model_name='nastock',
            name='tgoods_received',
            field=models.IntegerField(blank=True, db_column='TGoods_Received', null=True),
        ),
    ]
