# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-14 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0005_nagoodsoutwards_equipment_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagoodsoutwards',
            name='fk_receive',
            field=models.ForeignKey(db_column='FK_Receive', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_receive_nagoodsoutwards', to='NA_Models.NA_GoodsReceive_detail'),
        ),
    ]
