# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0006_auto_20180620_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nastock',
            name='totalqty',
            field=models.IntegerField(db_column='TotalQty', null=True),
        ),
    ]
