# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0007_auto_20191030_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagoodslending',
            name='statuslent',
            field=models.CharField(db_column='Status', default='L', max_length=10),
        ),
    ]
