# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0008_auto_20180620_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAGoodsHistory',
            fields=[
                ('idapp', models.AutoField(db_column='IDApp', primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField(db_column='CreatedDate')),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=100)),
                ('typeapp', models.CharField(db_column='TypeApp', max_length=32)),
                ('serialnumber', models.CharField(db_column='SerialNumber', max_length=100)),
                ('fk_disposal', models.ForeignKey(blank=True, db_column='FK_Disposal', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NADisposal')),
                ('fk_goods', models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods')),
                ('fk_lending', models.ForeignKey(blank=True, db_column='FK_Lending', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsLending')),
                ('fk_lost', models.ForeignKey(blank=True, db_column='FK_Lost', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsLost')),
                ('fk_maintenance', models.ForeignKey(blank=True, db_column='FK_Maintenance', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAMaintenance')),
                ('fk_outwards', models.ForeignKey(blank=True, db_column='FK_Outwards', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsOutwards')),
                ('fk_return', models.ForeignKey(blank=True, db_column='FK_Return', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.NAGoodsReturn')),
            ],
            options={
                'db_table': 'n_a_goods_history',
                'managed': True,
            },
        ),
    ]
