# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0009_auto_20191031_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAGoodsDeletion',
            fields=[
                ('idapp', models.AutoField(db_column='IDApp', primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField(db_column='CreatedDate', default=django.utils.timezone.now)),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=100)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True)),
                ('serialnumber', models.CharField(db_column='SerialNumber', default='N/A', max_length=100)),
                ('bookvalue', models.DecimalField(db_column='bookvalue', decimal_places=4, max_digits=30)),
                ('submission_value', models.DecimalField(db_column='submission_value', decimal_places=4, max_digits=30)),
                ('is_value_to_all', models.BooleanField(db_column='is_value_to_all')),
                ('approval_value', models.DecimalField(db_column='approval_value', decimal_places=4, max_digits=30)),
                ('acknowledged_by1', models.ForeignKey(db_column='acknowledged_by1', db_constraint=False, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_by_employee1', to='NA_Models.Employee')),
                ('acknowledged_by2', models.ForeignKey(db_column='acknowledged_by2', db_constraint=False, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_by_employee2', to='NA_Models.Employee')),
                ('approved_by', models.ForeignKey(db_column='fk_approvedby', db_constraint=False, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_employee', to='NA_Models.Employee')),
                ('fk_goods', models.ForeignKey(db_column='FK_Goods', db_constraint=False, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.goods')),
                ('submission_by', models.ForeignKey(db_column='fk_submission_by', db_constraint=False, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='submission_by_employee', to='NA_Models.Employee')),
                ('x_employee', models.ForeignKey(db_column='FK_Employee', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='NA_Models.Employee')),
            ],
            options={
                'db_table': 'n_a_goods_deletion',
                'managed': True,
            },
        ),
    ]
