# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-11-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0010_nagoodsdeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagoodsdeletion',
            name='submission_date',
            field=models.DateField(auto_now_add=True, db_column='submission_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='telphp',
            field=models.CharField(blank=True, db_column='TelpHP', max_length=20, null=True),
        ),
    ]
