# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-12-08 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Models', '0012_auto_20211208_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagoodslending',
            name='lastinfo',
            field=models.CharField(blank=True, db_column='lastinfo', max_length=250, null=True),
        ),
    ]
