# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 12:32
from __future__ import unicode_literals

import app.sessions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('user_id', models.IntegerField(db_column='user_id', db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'n_a_session',
                'abstract': False,
                'managed': True,
            },
            managers=[
                ('objects', app.sessions.NASessionManager()),
            ],
        ),
    ]
