# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-08 20:54
from __future__ import unicode_literals

import NA_DataLayer.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NANotifications',
            fields=[
                ('idapp', models.AutoField(db_column='idapp', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('title', models.CharField(db_column='title', max_length=150)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('data', NA_DataLayer.fields.JSONField(db_column='data', default=dict)),
                ('created_date', models.DateTimeField(db_column='created_date')),
                ('user', models.ManyToManyField(db_constraint=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'n_a_notifications',
                'managed': True,
            },
        ),
    ]
